version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports: ["3001:3000"]
    depends_on: [redis]