apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudwalk

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ingress.yaml
  - hpa.yaml
